import elections from "./elections.json";
import turnoutHistory from "./turnout_history.json";
import nightFloor from "./night_floor.json";
import vbmHistory from "./vbm_history.json";
import registrationEligible from "./registration_eligible.json";
import franchiseFunnel from "./franchise_funnel.json";
import countySpeed from "./county_speed.json";
import countyTech from "./county_tech.json";
import countyNight from "./county_night.json";
import sdNightHistory from "./sd_night_history.json";
import sources from "./sources.json";
import ledger from "./ledger.json";
import type {
  Election, TurnoutPoint, FloorPoint, VbmPoint, RegEligPoint, FunnelPoint,
  CountySpeed, CountyTech, CountyNight,
} from "./types";

export * from "./types";
export const ELECTIONS = elections as unknown as Election[];
export const TURNOUT_HISTORY = turnoutHistory as TurnoutPoint[];
export const NIGHT_FLOOR = nightFloor as FloorPoint[];
export const VBM_HISTORY = vbmHistory as VbmPoint[];
export const REGISTRATION_ELIGIBLE = registrationEligible as RegEligPoint[];
export const FRANCHISE_FUNNEL = franchiseFunnel as FunnelPoint[];
export const COUNTY_SPEED = countySpeed as CountySpeed;
export const COUNTY_TECH = countyTech as CountyTech;
export const COUNTY_NIGHT = countyNight as CountyNight;
// San Diego County's recovered night-count record (1871-1920 newspaper floors,
// certified-contest basis + 2008-2024 panel plateau rows, certified-ballots
// basis) in the chart Election shape. GENERATED by scripts/build_sd_history.py.
export const SD_NIGHT_HISTORY = (sdNightHistory as { elections: unknown[] })
  .elections as unknown as Election[];
// why each dimmed SD point is a lower bound (newspaper-practice artifacts and
// remote-AP-wire snapshots); keyed by election id.
export const SD_ARTIFACT_NOTES = (
  sdNightHistory as { artifactNotes: Record<string, string> }
).artifactNotes;
export const SOURCES = sources as Record<string, unknown>[];
export const LEDGER = ledger as { text: string };
