import { useState, useMemo } from "react";
import {
  LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid,
  ReferenceLine, ResponsiveContainer, Cell, LabelList, Tooltip,
  ScatterChart, Scatter, AreaChart, Area, ReferenceDot,
} from "recharts";

// SF vote-count timeline — data generated by `sfcount artifact` from
// data/sf_count_timeline.csv + data/sf_days_to_90.csv. Do not edit by hand.
// BEGIN GENERATED DATA
const E = [{"id":"2015-11-03","name":"Consolidated Municipal Election","kind":"Municipal","final":203069,"night":65.1,"d90":6,"pts":[[0.0,32.5,32.5,0.0],[0.0,44.7,32.5,12.2],[0.0,65.1,32.5,32.7],[0.17,69.4,36.7,32.7],[1.17,76.7,44.0,32.7],[2.17,84.8,52.1,32.7],[3.17,88.5,55.8,32.7],[4.17,89.3,56.6,32.7],[5.17,92.0,59.4,32.7],[6.17,96.1,61.0,35.0],[7.17,97.1,61.1,36.1],[8.17,99.9,61.9,38.0],[9.17,100.0,61.9,38.1],[12.17,100.0,61.9,38.1],[15.17,100.0,61.9,38.1]],"prov":false},
{"id":"2016-06-07","name":"Presidential Primary Election","kind":"Primary","final":264993,"night":70.1,"d90":4,"pts":[[0.0,36.4,36.4,0.0],[0.0,49.9,36.4,13.5],[0.0,69.6,36.4,33.2],[0.0,70.1,36.4,33.7],[0.17,72.8,39.2,33.7],[1.17,79.4,45.8,33.7],[2.17,84.9,51.2,33.7],[3.17,90.2,56.5,33.7],[4.17,91.0,57.3,33.7],[5.17,92.1,58.5,33.7],[6.17,93.0,59.4,33.7],[7.17,95.9,59.4,36.5],[8.17,97.0,60.0,37.0],[9.17,98.2,60.1,38.0],[12.17,99.7,60.3,39.4],[13.17,100.0,60.4,39.6],[16.17,100.0,60.4,39.6]],"prov":false},
{"id":"2016-11-08","name":"Consolidated General Election","kind":"General","final":414528,"night":66.1,"d90":9,"pts":[[0.0,34.3,34.3,0.0],[0.07,47.2,34.3,12.9],[0.12,66.0,34.3,31.7],[0.17,66.1,34.3,31.8],[0.83,66.9,35.1,31.8],[1.83,68.3,36.5,31.8],[2.82,69.2,37.4,31.8],[3.84,71.5,39.7,31.8],[4.84,75.3,43.5,31.8],[5.83,78.2,46.4,31.8],[6.84,82.2,50.4,31.8],[7.83,86.1,54.3,31.8],[8.85,90.4,58.6,31.8],[9.84,92.9,61.1,31.8],[10.83,94.9,62.7,32.2],[11.83,95.7,63.0,32.7],[12.83,98.0,63.4,34.6],[13.9,99.9,63.5,36.5],[14.83,100.0,63.5,36.5],[19.87,100.0,63.5,36.5],[22.83,100.0,63.5,36.5],[27.77,100.0,63.5,36.5]],"prov":false},
{"id":"2018-06-05","name":"Consolidated Statewide Primary Election","kind":"Primary","final":253583,"night":60.8,"d90":6,"pts":[[0.04,31.2,31.2,0.0],[0.09,48.6,31.2,17.5],[0.12,60.7,31.2,29.6],[0.17,60.8,31.2,29.7],[0.83,62.7,33.0,29.7],[1.84,65.9,36.2,29.7],[2.84,73.5,43.9,29.7],[3.83,82.7,53.0,29.7],[4.83,89.2,59.5,29.7],[5.83,92.7,63.1,29.7],[6.82,96.4,63.8,32.6],[7.83,97.5,64.0,33.4],[8.83,98.4,64.1,34.4],[9.84,99.7,64.6,35.2],[12.85,100.0,64.6,35.4],[15.84,100.0,64.6,35.4],[21.83,100.0,64.6,35.4]],"prov":false},
{"id":"2018-11-06","name":"General Election","kind":"General","final":372848,"night":59.3,"d90":7,"pts":[[0.04,31.9,31.9,0.0],[0.07,41.5,31.9,9.6],[0.11,58.9,31.9,27.1],[0.21,59.3,31.9,27.4],[0.83,63.1,35.7,27.4],[1.83,65.1,37.6,27.4],[2.83,67.8,40.4,27.4],[3.82,73.4,45.9,27.4],[4.83,80.5,53.1,27.4],[5.84,86.7,59.3,27.5],[6.83,90.7,63.1,27.6],[7.82,92.7,63.8,28.9],[8.83,95.9,64.1,31.8],[9.85,98.0,64.5,33.5],[10.83,99.4,65.6,33.8],[12.84,99.8,65.6,34.1],[13.83,99.9,65.7,34.2],[19.83,100.0,65.7,34.3],[20.82,100.0,65.7,34.3]],"prov":false},
{"id":"2019-11-05","name":"Consolidated Municipal Election","kind":"Municipal","final":206122,"night":55.9,"d90":3,"pts":[[0.03,33.8,33.8,0.0],[0.07,51.3,null,null],[0.12,55.9,null,null],[0.19,55.9,33.8,22.1],[0.84,64.8,42.7,22.1],[1.84,79.4,57.3,22.1],[2.86,92.4,70.3,22.1],[3.83,99.4,71.1,28.2],[4.83,100.0,71.1,28.8],[6.83,100.0,71.1,28.8],[7.84,100.0,71.1,28.8],[8.84,100.0,71.2,28.8],[20.82,100.0,null,null]],"prov":false},
{"id":"2020-03-03","name":"Presidential Primary Election","kind":"Primary","final":305184,"night":47.4,"d90":4,"pts":[[0.03,23.7,23.7,0.0],[0.07,33.8,23.7,10.1],[0.12,47.4,23.7,23.7],[0.2,47.4,23.7,23.7],[0.84,59.0,35.3,23.7],[1.9,78.9,55.2,23.7],[2.84,87.1,63.4,23.7],[3.83,90.2,64.5,25.7],[5.84,92.4,64.6,27.8],[6.84,96.0,64.7,31.3],[7.83,98.8,64.8,34.0],[8.85,99.9,64.9,35.0],[9.85,100.0,64.9,35.1],[22.17,100.0,64.9,35.1]],"prov":false},
{"id":"2020-11-03","name":"Consolidated General Election","kind":"General","final":449866,"night":78.4,"d90":3,"pts":[[0.04,71.6,71.6,0.0],[0.08,76.9,71.6,5.3],[0.11,78.3,71.6,6.8],[0.2,78.4,71.6,6.8],[0.84,78.6,71.8,6.8],[1.83,85.2,78.4,6.8],[2.84,93.1,86.3,6.9],[3.85,97.2,89.9,7.3],[4.83,98.6,90.6,8.0],[5.84,99.3,90.8,8.5],[6.84,99.7,91.2,8.5],[8.83,99.8,91.3,8.5],[9.83,99.9,91.3,8.5],[13.84,99.9,91.3,8.5],[15.83,99.9,91.4,8.5],[20.83,100.0,91.4,8.5],[27.86,100.0,91.5,8.5]],"prov":false},
{"id":"2021-09-14","name":"California Gubernatorial Recall Election","kind":"Recall","final":341055,"night":78.7,"d90":3,"pts":[[0.03,72.2,72.2,0.0],[0.07,76.5,72.2,4.3],[0.11,78.6,72.2,6.4],[0.14,78.7,72.2,6.4],[0.83,79.0,72.6,6.4],[1.83,86.7,80.3,6.4],[2.84,93.7,87.3,6.4],[3.81,96.9,90.5,6.4],[5.83,98.7,90.5,8.2],[6.84,99.8,91.4,8.4],[7.83,99.9,91.5,8.4],[16.83,100.0,91.5,8.5],[20.82,100.0,91.5,8.5]],"prov":false},
{"id":"2022-02-15","name":"Consolidated Special Municipal Election","kind":"Special","final":179981,"night":72.4,"d90":3,"pts":[[0.02,66.5,66.5,0.0],[0.07,71.6,66.5,5.1],[0.11,72.4,66.5,5.9],[1.83,83.0,77.1,5.9],[2.83,97.0,91.1,5.9],[3.8,99.7,93.1,6.6],[6.82,99.9,93.3,6.6],[7.83,100.0,93.4,6.6]],"prov":false},
{"id":"2022-04-19","name":"Special General Election","kind":"Special","final":78764,"night":78.7,"d90":2,"pts":[[0.03,74.5,74.5,0.0],[0.07,78.7,74.5,4.2],[0.09,78.7,74.5,4.2],[1.83,99.0,94.8,4.2],[2.83,99.9,95.2,4.7],[7.84,100.0,95.3,4.7],[8.83,100.0,95.3,4.7]],"prov":false},
{"id":"2022-06-07","name":"Consolidated Statewide Direct Primary Election","kind":"Primary","final":229229,"night":55.8,"d90":4,"pts":[[0.03,47.6,47.6,0.0],[0.07,52.7,47.6,5.0],[0.11,55.8,47.6,8.2],[0.15,55.8,47.6,8.2],[1.83,61.9,53.7,8.2],[2.83,80.5,72.4,8.2],[3.83,96.9,88.8,8.2],[4.79,99.4,89.8,9.6],[6.83,99.9,90.2,9.6],[8.83,100.0,90.3,9.7],[14.82,100.0,90.3,9.7]],"prov":false},
{"id":"2022-11-08","name":"Consolidated General Election","kind":"General","final":310071,"night":51.0,"d90":7,"pts":[[0.03,42.7,42.7,0.0],[0.06,46.3,42.7,3.7],[0.11,51.0,42.7,8.3],[0.17,51.0,42.7,8.4],[1.83,54.1,45.8,8.4],[2.83,63.0,54.6,8.4],[3.83,72.5,64.2,8.4],[4.83,79.5,71.1,8.4],[5.83,86.8,78.4,8.4],[6.83,94.1,85.7,8.4],[7.83,97.5,87.0,10.5],[8.83,99.0,87.7,11.4],[9.83,99.7,88.3,11.4],[13.83,100.0,88.5,11.5],[20.83,100.0,88.5,11.5],[22.82,100.0,88.5,11.5]],"prov":false},
{"id":"2024-03-05","name":"Presidential Primary Election","kind":"Primary","final":233465,"night":44.9,"d90":4,"pts":[[0.03,35.6,35.6,0.0],[0.07,39.0,35.6,3.3],[0.11,44.8,35.6,9.2],[0.16,44.9,35.6,9.2],[1.83,56.6,47.3,9.2],[2.83,82.8,73.6,9.2],[3.83,92.6,83.4,9.2],[5.83,95.4,86.1,9.2],[6.83,96.5,87.2,9.4],[7.83,97.1,87.3,9.8],[8.84,98.2,87.3,10.9],[9.84,99.9,88.0,12.0],[14.83,100.0,88.0,12.0],[15.83,100.0,88.0,12.0],[16.82,100.0,88.0,12.0]],"prov":false},
{"id":"2024-11-05","name":"Consolidated General Election","kind":"General","final":412231,"night":56.9,"d90":6,"pts":[[0.03,47.8,47.8,0.0],[0.06,50.4,47.8,2.5],[0.11,56.5,47.8,8.7],[0.19,56.9,47.8,9.1],[1.83,62.9,53.8,9.1],[2.82,70.1,61.0,9.1],[3.82,78.9,69.7,9.2],[4.83,88.5,79.3,9.3],[5.82,92.7,83.0,9.7],[6.82,94.3,84.2,10.1],[7.82,94.7,84.6,10.1],[8.82,96.2,85.2,11.0],[9.82,97.9,85.3,12.5],[10.83,99.4,85.5,13.9],[12.82,99.9,85.6,14.2],[13.84,100.0,85.7,14.3],[15.82,100.0,85.7,14.2],[27.79,100.0,85.8,14.2]],"prov":false},
{"id":"2025-09-16","name":"Special Recall Election","kind":"Recall","final":21542,"night":76.5,"d90":2,"pts":[[0.03,71.8,71.8,0.0],[0.11,76.5,71.8,4.7],[1.82,98.7,94.0,4.7],[8.81,100.0,94.6,5.4]],"prov":false},
{"id":"2025-11-04","name":"Statewide Special Election","kind":"Special","final":295232,"night":66.4,"d90":13,"pts":[[0.02,59.2,59.2,0.0],[0.14,66.4,59.2,7.2],[1.82,70.8,63.6,7.2],[5.81,89.9,82.7,7.2],[12.81,98.9,90.2,8.7],[19.81,99.9,90.3,9.6],[28.79,100.0,90.4,9.6]],"prov":false},
{"id":"2026-06-02","name":"Consolidated Statewide Direct Primary Election","kind":"Primary","final":259288,"night":48.2,"d90":7,"pts":[[0.03,38.9,38.9,0.0],[0.07,41.9,38.9,3.0],[0.1,48.2,38.9,9.3],[0.18,48.2,38.9,9.4],[1.83,54.1,44.8,9.4],[2.83,68.1,58.7,9.4],[5.83,86.0,76.6,9.4],[6.83,100.0,90.6,9.4]],"prov":true}];
// END GENERATED DATA

const C = {
  paper: "#F7F3EB", ink: "#2B2620", faint: "#8A7C68", rule: "#D8D0C0",
  accent: "#9C4A2F", general: "#3D3A33", other: "#A39681",
};
const serif = "'Source Serif 4', Georgia, serif";
const mono = "'IBM Plex Mono', ui-monospace, monospace";
const fmt = (n) => n.toLocaleString("en-US");
const seriesOf = (e) => e.pts.map(([d, p]) => ({ d, p }));
const splitOf = (e) => e.pts.map(([d, p, v, ed]) => ({ d, v, ed }));
const hasSplit = (e) => e.pts.some((p) => p[2] != null);
// Filter buckets: Municipal elections are regularly scheduled local generals;
// recalls are unscheduled, so they group with specials.
const CATS = ["Primary", "General", "Special"];
const catOf = (e) =>
  e.kind === "Primary" ? "Primary"
  : e.kind === "General" || e.kind === "Municipal" ? "General"
  : "Special";

function Trajectories({ els, sel, setSel }) {
  const selEl = els.find((e) => e.id === sel);
  return (
    <div>
      <ResponsiveContainer width="100%" height={440}>
        <LineChart margin={{ top: 20, right: 70, bottom: 28, left: 8 }}>
          <CartesianGrid stroke={C.rule} vertical={false} />
          <XAxis
            type="number" dataKey="d" domain={[0, 14]}
            ticks={[0, 2, 4, 6, 8, 10, 12, 14]} allowDataOverflow
            stroke={C.faint} tickLine={false}
            tick={{ fontFamily: mono, fontSize: 11, fill: C.faint }}
            label={{ value: "DAYS SINCE ELECTION", position: "insideBottom",
                     offset: -16, fontFamily: mono, fontSize: 11,
                     letterSpacing: "0.1em", fill: C.faint }} />
          <YAxis
            type="number" dataKey="p" domain={[20, 100]}
            ticks={[20, 40, 60, 80, 100]} stroke={C.faint} tickLine={false}
            tick={{ fontFamily: mono, fontSize: 11, fill: C.faint }}
            tickFormatter={(v) => `${v}%`} width={44} />
          <ReferenceLine
            y={90} stroke={C.accent} strokeWidth={1.25} ifOverflow="visible"
            label={{ value: "90% COUNTED", position: "right", fontFamily: mono,
                     fontSize: 10, fill: C.accent }} />
          {/* Archival recovery: Wayback capture of the live 2012 results page,
              self-dated Nov 11 2012 16:28 — 325,298 of 364,875 certified. */}
          <ReferenceDot x={4.85} y={89.2} r={4} fill={C.paper} stroke={C.ink}
            strokeWidth={1.5} ifOverflow="visible"
            label={{ value: "NOV 2012 (ARCHIVED): 89.2% ON DAY 4.85",
                     position: "bottom", fontFamily: mono, fontSize: 10,
                     fill: C.ink }} />
          {els.map((e) => {
            const active = sel === e.id;
            return (
              <Line
                key={e.id} data={seriesOf(e)} dataKey="p" type="linear"
                name={e.id} isAnimationActive={false}
                stroke={active ? C.accent
                  : e.kind === "General" ? C.general : C.other}
                strokeWidth={active ? 2.25 : 1.1}
                strokeDasharray={e.prov ? "5 4" : undefined}
                strokeOpacity={sel && !active ? 0.32 : 1}
                dot={active ? { r: 2.5, fill: C.accent, stroke: "none" } : false}
                activeDot={false}
                style={{ cursor: "pointer" }}
                onMouseEnter={() => setSel(e.id)}
                onClick={() => setSel(active ? null : e.id)} />
            );
          })}
        </LineChart>
      </ResponsiveContainer>
      <div style={{ fontFamily: mono, fontSize: 12, color: C.ink,
                    minHeight: 18, marginTop: 2 }}>
        {selEl && `${selEl.id} — ${fmt(selEl.final)} ballots — 90% on day ${selEl.d90}${selEl.prov ? " (count in progress)" : ""}`}
      </div>
    </div>
  );
}

function DaysBars({ els, sel, setSel }) {
  const data = els.map((e) => ({ ...e, label: `${e.d90}d` }));
  return (
    <ResponsiveContainer width="100%" height={els.length * 27 + 20}>
      <BarChart data={data} layout="vertical"
                margin={{ top: 0, right: 36, bottom: 0, left: 0 }}>
        <XAxis type="number" domain={[0, 14]} hide />
        <YAxis
          type="category" dataKey="id" width={94} stroke="none" tickLine={false}
          tick={{ fontFamily: mono, fontSize: 11.5, fill: C.faint }} />
        <Bar dataKey="d90" barSize={11} isAnimationActive={false}
             onMouseEnter={(d) => setSel(d.id)}
             onClick={(d) => setSel(sel === d.id ? null : d.id)}
             style={{ cursor: "pointer" }}>
          {data.map((e) => (
            <Cell key={e.id}
                  fill={sel === e.id ? C.accent
                    : e.kind === "General" ? C.general : C.other}
                  fillOpacity={e.prov ? 0.55 : sel && sel !== e.id ? 0.45 : 1} />
          ))}
          <LabelList dataKey="label" position="right"
                     style={{ fontFamily: mono, fontSize: 11, fill: C.ink }} />
        </Bar>
      </BarChart>
    </ResponsiveContainer>
  );
}

function YearTrend({ els, sel, setSel }) {
  const data = els.map((e) => {
    const d = new Date(e.id + "T12:00:00");
    return { ...e, yr: d.getFullYear() + (d.getMonth() + 0.5) / 12 };
  });
  const years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026];
  const axis = (extra) => ({
    type: "number", dataKey: "yr", domain: [2015, 2026.9],
    ticks: years, stroke: C.faint, tickLine: false,
    tick: { fontFamily: mono, fontSize: 11, fill: C.faint },
    tickFormatter: (v) => String(v), ...extra,
  });
  const dot = (e) => ({
    fill: sel === e.id ? C.accent : e.kind === "General" ? C.general : C.other,
    fillOpacity: e.prov ? 0.55 : sel && sel !== e.id ? 0.5 : 1,
  });
  const handlers = {
    onMouseEnter: (d) => setSel(d.id),
    onClick: (d) => setSel(sel === d.id ? null : d.id),
    style: { cursor: "pointer" },
    isAnimationActive: false,
  };
  return (
    <div>
      <div style={{ fontFamily: mono, fontSize: 10, letterSpacing: "0.12em",
                    color: C.faint, margin: "0 0 2px 48px" }}>DAYS TO 90% COUNTED</div>
      <ResponsiveContainer width="100%" height={180}>
        <ScatterChart margin={{ top: 8, right: 24, bottom: 4, left: 8 }}>
          <CartesianGrid stroke={C.rule} vertical={false} />
          <XAxis {...axis({ tick: false, axisLine: { stroke: C.rule }, height: 4 })} />
          <YAxis type="number" dataKey="d90" domain={[0, 14]} ticks={[0, 5, 10]}
                 stroke={C.faint} tickLine={false} width={44}
                 tick={{ fontFamily: mono, fontSize: 11, fill: C.faint }} />
          <Scatter data={data} shape="square" {...handlers}>
            {data.map((e) => <Cell key={e.id} {...dot(e)} />)}
          </Scatter>
        </ScatterChart>
      </ResponsiveContainer>
      <div style={{ fontFamily: mono, fontSize: 10, letterSpacing: "0.12em",
                    color: C.faint, margin: "10px 0 2px 48px" }}>% COUNTED BY MIDNIGHT, ELECTION NIGHT</div>
      <ResponsiveContainer width="100%" height={200}>
        <ScatterChart margin={{ top: 8, right: 24, bottom: 24, left: 8 }}>
          <CartesianGrid stroke={C.rule} vertical={false} />
          <XAxis {...axis()} />
          <YAxis type="number" dataKey="night" domain={[40, 80]} ticks={[40, 60, 80]}
                 stroke={C.faint} tickLine={false} width={44}
                 tickFormatter={(v) => `${v}%`}
                 tick={{ fontFamily: mono, fontSize: 11, fill: C.faint }} />
          <Scatter data={data} shape="square" {...handlers}>
            {data.map((e) => <Cell key={e.id} {...dot(e)} />)}
          </Scatter>
        </ScatterChart>
      </ResponsiveContainer>
    </div>
  );
}

function SplitArea({ el }) {
  if (!el) return null;
  if (!hasSplit(el)) {
    return (
      <p style={{ fontFamily: mono, fontSize: 12, color: C.faint,
                  border: `1px solid ${C.rule}`, padding: 14 }}>
        The {el.id} report format published no vote-by-mail /
        election-day breakdown.
      </p>
    );
  }
  return (
    <div>
      <ResponsiveContainer width="100%" height={210}>
        <AreaChart data={splitOf(el)}
                   margin={{ top: 6, right: 8, bottom: 4, left: 8 }}>
          <CartesianGrid stroke={C.rule} vertical={false} />
          <XAxis type="number" dataKey="d" domain={[0, 14]}
                 ticks={[0, 2, 4, 6, 8, 10, 12, 14]} stroke={C.faint}
                 tickLine={false}
                 tick={{ fontFamily: mono, fontSize: 10, fill: C.faint }} />
          <YAxis type="number" domain={[0, 100]} ticks={[0, 50, 100]}
                 width={40} stroke={C.faint} tickLine={false}
                 tickFormatter={(v) => `${v}%`}
                 tick={{ fontFamily: mono, fontSize: 10, fill: C.faint }} />
          <Area dataKey="v" stackId="s" type="stepAfter" isAnimationActive={false}
                stroke="#5B6350" strokeWidth={1.25} fill="#5B6350" fillOpacity={0.55} />
          <Area dataKey="ed" stackId="s" type="stepAfter" isAnimationActive={false}
                stroke="#B7A88D" strokeWidth={1.25} fill="#C9BCA4" fillOpacity={0.6} />
        </AreaChart>
      </ResponsiveContainer>
      <div style={{ fontFamily: mono, fontSize: 11, color: C.faint,
                    display: "flex", gap: 20, marginTop: 4 }}>
        <span><span style={{ display: "inline-block", width: 12, height: 9,
          background: "#5B6350", opacity: 0.7, marginRight: 6,
          verticalAlign: "middle" }} />vote-by-mail</span>
        <span><span style={{ display: "inline-block", width: 12, height: 9,
          background: "#C9BCA4", marginRight: 6,
          verticalAlign: "middle" }} />election day (in person + precinct)</span>
      </div>
    </div>
  );
}

export default function App() {
  const [sel, setSel] = useState("2024-11-05");
  const [cats, setCats] = useState(() => new Set(CATS));
  const els = useMemo(() => E.filter((e) => cats.has(catOf(e))), [cats]);
  const toggleCat = (c) => {
    const next = new Set(cats);
    next.has(c) ? next.delete(c) : next.add(c);
    if (next.size === 0) return; // keep at least one bucket on
    setCats(next);
    if (sel && !E.filter((e) => next.has(catOf(e))).some((e) => e.id === sel)) setSel(null);
  };
  const stats = useMemo(() => ({
    releases: els.reduce((n, e) => n + e.pts.length, 0),
    nights: [Math.min(...els.map((e) => e.night)), Math.max(...els.map((e) => e.night))],
    d90s: [Math.min(...els.map((e) => e.d90)), Math.max(...els.map((e) => e.d90))],
  }), [els]);
  const selEl = els.find((e) => e.id === sel);

  return (
    <div style={{ background: C.paper, color: C.ink, minHeight: "100vh" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Source+Serif+4:opsz,wght@8..60,400;8..60,600;8..60,700&family=IBM+Plex+Mono:wght@400;500&display=swap');
        * { box-sizing: border-box; }
      `}</style>

      <div style={{ maxWidth: 920, margin: "0 auto", padding: "48px 24px 64px" }}>
        <header style={{ borderBottom: `2px solid ${C.ink}`, paddingBottom: 20 }}>
          <div style={{ fontFamily: mono, fontSize: 11, letterSpacing: "0.14em",
                        color: C.faint, marginBottom: 14 }}>
            SF DEPARTMENT OF ELECTIONS · PRELIMINARY RESULTS REPORTS · NOV 2015 – JUN 2026
          </div>
          <h1 style={{ fontFamily: serif, fontWeight: 700, fontSize: 44,
                       lineHeight: 1.05, margin: 0 }}>The Long Count</h1>
          <p style={{ fontFamily: serif, fontSize: 18, lineHeight: 1.5,
                      maxWidth: "62ch", margin: "14px 0 0", color: "#4A443A" }}>
            How long San Francisco takes to count its ballots. Each line is one
            election: the share of the eventual final count reported, by days
            since election day. Every release the Department published, from the
            8:45&nbsp;p.m. election-night report through certification.
          </p>
        </header>

        <div style={{ display: "flex", flexWrap: "wrap",
                      borderBottom: `1px solid ${C.rule}` }}>
          {[
            ["ELECTIONS", String(els.length)],
            ["RELEASES \u2264 DAY 14", String(stats.releases)],
            ["COUNTED BY MIDNIGHT", `${stats.nights[0]}–${stats.nights[1]}%`],
            ["DAYS TO 90%", `${stats.d90s[0]}–${stats.d90s[1]}`],
          ].map(([k, v], i, arr) => (
            <div key={k} style={{ padding: "16px 28px 16px 0", marginRight: 28,
                                  borderRight: i < arr.length - 1
                                    ? `1px solid ${C.rule}` : "none" }}>
              <div style={{ fontFamily: mono, fontSize: 22, fontWeight: 500 }}>{v}</div>
              <div style={{ fontFamily: mono, fontSize: 10, letterSpacing: "0.12em",
                            color: C.faint, marginTop: 2 }}>{k}</div>
            </div>
          ))}
        </div>

        <div style={{ display: "flex", gap: 10, marginTop: 20 }}>
          {CATS.map((c) => {
            const on = cats.has(c);
            return (
              <button key={c} onClick={() => toggleCat(c)}
                style={{ fontFamily: mono, fontSize: 11, letterSpacing: "0.1em",
                         padding: "7px 14px", cursor: "pointer", borderRadius: 0,
                         border: `1px solid ${on ? C.ink : C.rule}`,
                         background: on ? C.ink : "transparent",
                         color: on ? C.paper : C.faint }}>
                {c.toUpperCase()}
              </button>
            );
          })}
          <span style={{ fontFamily: mono, fontSize: 11, color: C.faint,
                         alignSelf: "center", marginLeft: 6 }}>
            municipal counts as general; recalls count as special
          </span>
        </div>

        <section style={{ marginTop: 36 }}>
          <Trajectories els={els} sel={sel} setSel={setSel} />
          <div style={{ fontFamily: mono, fontSize: 11, color: C.faint,
                        display: "flex", flexWrap: "wrap", gap: 24, marginTop: 8 }}>
            <span><span style={{ display: "inline-block", width: 18, height: 2,
              background: C.general, verticalAlign: "middle", marginRight: 6 }} />general elections</span>
            <span><span style={{ display: "inline-block", width: 18, height: 2,
              background: C.other, verticalAlign: "middle", marginRight: 6 }} />primaries · municipal · special</span>
            <span><span style={{ display: "inline-block", width: 18, height: 0,
              borderTop: `2px dashed ${C.other}`, verticalAlign: "middle", marginRight: 6 }} />count in progress</span>
          </div>
        </section>

        <section style={{ marginTop: 48 }}>
          <h2 style={{ fontFamily: serif, fontSize: 22, fontWeight: 600,
                       margin: "0 0 6px" }}>By year: is the count getting slower?</h2>
          <p style={{ fontFamily: serif, fontSize: 15, lineHeight: 1.55,
                      color: "#4A443A", maxWidth: "70ch", margin: "0 0 16px" }}>
            Within this window, no. Days-to-90% shows no upward trend from 2015
            to 2026 (+0.01 days per year across all elections; general
            elections alone trend slightly <em>down</em>, pulled by 2020's
            early-processed pandemic count). What predicts a slow count is not
            the year — it's election size (correlation +0.44) and how little
            was counted by midnight (−0.30). The structural slowdown from the
            shift to universal vote-by-mail predates this window; testing it
            requires the pre-2015 data.
          </p>
          <YearTrend els={els} sel={sel} setSel={setSel} />
        </section>

        <section style={{ marginTop: 48, display: "grid",
                          gridTemplateColumns: "minmax(280px, 1fr) minmax(280px, 1.1fr)",
                          gap: 40 }}>
          <div>
            <h2 style={{ fontFamily: serif, fontSize: 22, fontWeight: 600,
                         margin: "0 0 12px" }}>Days to 90% counted</h2>
            <DaysBars els={els} sel={sel} setSel={setSel} />
          </div>
          <div>
            <h2 style={{ fontFamily: serif, fontSize: 22, fontWeight: 600,
                         margin: "0 0 12px" }}>
              {selEl ? selEl.name : "Select an election"}
            </h2>
            {selEl && (
              <table style={{ width: "100%", borderCollapse: "collapse",
                              fontFamily: mono, fontSize: 13 }}>
                <tbody>
                  {[
                    ["Election", selEl.id],
                    ["Type", selEl.kind],
                    ["Final ballots", fmt(selEl.final) + (selEl.prov ? " (to date)" : "")],
                    ["Counted by midnight", `${selEl.night}%`],
                    ["First report ≥ 90%", `day ${selEl.d90}`],
                    ["Releases \u2264 day 14", String(selEl.pts.length)],
                  ].map(([k, v]) => (
                    <tr key={k} style={{ borderBottom: `1px solid ${C.rule}` }}>
                      <td style={{ padding: "8px 0", color: C.faint }}>{k}</td>
                      <td style={{ padding: "8px 0", textAlign: "right" }}>{v}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
            <div style={{ marginTop: 18 }}>
              <div style={{ fontFamily: mono, fontSize: 10,
                            letterSpacing: "0.12em", color: C.faint,
                            marginBottom: 4 }}>
                SHARE OF FINAL COUNT BY SOURCE, PER RELEASE
              </div>
              <SplitArea el={selEl} />
            </div>
            <p style={{ fontFamily: serif, fontSize: 15, lineHeight: 1.55,
                        color: "#4A443A", marginTop: 18 }}>
              The pattern repeats: a large election-night batch — every mail
              ballot received and processed before election day — then a pause,
              then a days-long crawl through the ballots that arrived on or
              just before election day. Bigger, later-arriving vote-by-mail
              volume stretches the crawl.
            </p>
          </div>
        </section>

        <footer style={{ marginTop: 56, paddingTop: 16,
                         borderTop: `1px solid ${C.rule}`,
                         fontFamily: mono, fontSize: 11, lineHeight: 1.7,
                         color: C.faint, maxWidth: "78ch" }}>
          NOTES — Source: per-release summary reports, sfelections.org/results.
          “Days to 90%” is the first published report at or above 90% of the
          final ballot count; no interpolation between releases. Nov 2025’s
          13-day figure partly reflects a sparser release cadence (only seven
          reports). Jun 2026 is uncertified; its denominator is the count to
          date. Per-release data before Nov 2015 is not on the live site; the Nov 2012 point was recovered from an Archive-It capture of the then-live results page (VBM 174,755 / election day 150,543 of 364,875 certified) and is excluded from days-to-90 statistics.
        </footer>
      </div>
    </div>
  );
}
