#!/usr/bin/env python3
"""Generate docs/sources.md and docs/missing.md from the data files.

Do not edit the output files by hand — re-run this script instead.
"""

import csv
import json
import os
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
SOURCES_JSON = REPO_ROOT / "packages" / "data" / "sources.json"
ELECTIONS_CSV = REPO_ROOT / "data" / "elections_master.csv"
LEDGER_JSON = REPO_ROOT / "packages" / "data" / "ledger.json"
DOCS_DIR = REPO_ROOT / "docs"

GENERATED_NOTE = (
    "<!-- Generated by scripts/gen_docs.py — do not edit by hand. "
    "Re-run the script to update. -->\n\n"
)


def gen_sources_md() -> str:
    with open(SOURCES_JSON, encoding="utf-8") as f:
        records = json.load(f)

    # Stable order: keep file order (records already have stable IDs)
    lines: list[str] = [GENERATED_NOTE]
    lines.append("# Data sources\n\n")
    lines.append(
        "Every number in the Long Count dataset traces to a primary source. "
        f"This file documents all {len(records)} source records — what was "
        "consulted, what it established, and where to find it.\n\n"
    )
    lines.append(
        "These records were previously displayed on the `/sources` page of "
        "the viz app. They now live here as a stable, version-controlled "
        "reference in the data repository.\n\n"
    )
    lines.append("---\n\n")

    for record in records:
        record_id = record.get("id", "")
        name = record.get("name", record_id or "(unnamed)")
        summary = record.get("summary", "").strip()
        final = record.get("final")
        final_source = record.get("finalSource", "").strip()
        observations = record.get("observations", [])

        lines.append(f"### {name}\n\n")
        if record_id:
            lines.append(f"**ID:** `{record_id}`\n\n")
        if summary:
            lines.append(f"{summary}\n\n")
        if final is not None:
            lines.append(f"**Certified final:** {final:,}\n\n")
        if final_source:
            lines.append(f"**Source:** {final_source}\n\n")
        if observations:
            lines.append("**Observations**\n\n")
            lines.append(
                "| Date | Days after | Election night | Count | % of final | Source |\n"
            )
            lines.append(
                "|------|-----------:|:--------------:|------:|-----------:|--------|\n"
            )
            for obs in observations:
                date = str(obs.get("date", "")).strip()
                days = obs.get("days")
                days = "" if days is None else str(days)
                night = "✓" if obs.get("night") else ""
                total = obs.get("total")
                total = "" if total is None else f"{total:,}"
                pct = obs.get("pct")
                pct = "" if pct is None else f"{pct}%"
                label = str(obs.get("label", "")).strip()
                citation = str(obs.get("citation", "")).strip()
                source = " — ".join(s for s in (label, citation) if s)
                source = source.replace("|", "&#124;")
                lines.append(
                    f"| {date} | {days} | {night} | {total} | {pct} | {source} |\n"
                )
            lines.append("\n")
        lines.append("---\n\n")

    return "".join(lines)


def gen_missing_md() -> str:
    with open(ELECTIONS_CSV, encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    # "missing" = every election without a recovered night count; among them,
    # `final-only` rows have a known certified/registrar final and `no` rows
    # have no recovered data at all (operator category ruling, 2026-07-07)
    missing = [r for r in rows if r.get("recovered", "").strip().lower() != "night"]
    # Stable sort: by election_date (already ISO-ish strings, lexicographic == chronological)
    missing.sort(key=lambda r: r.get("election_date", ""))
    n_final = sum(1 for r in missing if r.get("recovered", "").strip().lower() == "final-only")

    with open(LEDGER_JSON, encoding="utf-8") as f:
        ledger = json.load(f)
    ledger_text = ledger.get("text", "").strip()

    count = len(missing)

    lines: list[str] = [GENERATED_NOTE]
    lines.append("# Missing election-night counts — help wanted\n\n")
    if count == n_final:
        lines.append(
            f"**{count} San Francisco elections still lack an election-night ballot "
            "count — but every one of them has a known final count** (a certified, "
            "registrar, or official-canvass total; `recovered = final-only`), so as "
            "of July 2026 no election lacks recovered data entirely. The list lives "
            "in [`data/elections_master.csv`](../data/elections_master.csv). "
            "None are lost causes: the returns were printed at the time and most "
            "survive in the newspaper archive. You can help find them — no special "
            "skills needed.\n\n"
        )
    else:
        lines.append(
            f"**{count} San Francisco elections still lack an election-night ballot count.** "
            f"For {n_final} of them we at least hold the final count (a certified or "
            "registrar total; `recovered = final-only`); the other "
            f"{count - n_final} have no recovered data at all (`recovered = no`). "
            "Both live in "
            "[`data/elections_master.csv`](../data/elections_master.csv). "
            "None are lost causes: the returns were printed at the time and most "
            "survive in the newspaper archive. You can help find them — no special "
            "skills needed.\n\n"
        )
    lines.append(
        "This page was previously the `/missing` route in the viz app. "
        "It now lives here as a stable, version-controlled reference in the "
        "data repository.\n\n"
    )
    lines.append(
        "**How to contribute:** open a pull request adding the source and "
        "figures to the relevant file in `data/`, or email "
        "[contact@growsf.org](mailto:contact@growsf.org) with a photo/scan, "
        "the election date, which contest, and where you found it. "
        "See [README.md](../README.md) for the full how-to-look guide.\n\n"
    )
    lines.append("---\n\n")
    lines.append(f"## The {count} elections still missing a night count\n\n")

    # Table
    lines.append("| Date | Year | Level | Kind | Final count known? | Description |\n")
    lines.append("|------|------|-------|------|--------------------|-------------|\n")
    for r in missing:
        date = r.get("election_date", "").strip()
        year = r.get("year", "").strip()
        level = r.get("level", "").strip()
        kind = r.get("kind", "").strip()
        has_final = "yes" if r.get("recovered", "").strip().lower() == "final-only" else "no"
        description = r.get("description", "").strip().replace("|", "&#124;")
        lines.append(f"| {date} | {year} | {level} | {kind} | {has_final} | {description} |\n")

    lines.append("\n---\n\n")

    # Verbatim search log
    lines.append(ledger_text)
    lines.append("\n")

    return "".join(lines)


def main() -> None:
    DOCS_DIR.mkdir(exist_ok=True)

    sources_path = DOCS_DIR / "sources.md"
    missing_path = DOCS_DIR / "missing.md"

    sources_content = gen_sources_md()
    missing_content = gen_missing_md()

    sources_path.write_text(sources_content, encoding="utf-8")
    missing_path.write_text(missing_content, encoding="utf-8")

    print(f"Wrote {sources_path} ({sources_path.stat().st_size:,} bytes)")
    print(f"Wrote {missing_path} ({missing_path.stat().st_size:,} bytes)")

    # keep the consolidated one-file export in lockstep with the datasets
    import subprocess
    import sys
    subprocess.run([sys.executable, str(Path(__file__).parent / "build_consolidated_export.py")],
                   check=True)


if __name__ == "__main__":
    main()
